apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: kafka
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: kafka-producer:latest

