---
- name: Copy kubeadm-config
  template:
    src: "{{ role_path }}/templates/kubeadm-config.yaml"
    dest: /root/kubeadm-config.yaml

- name: Copy ca.pem
  copy:
    src: "{{ role_path }}/files/ca.pem"
    dest: /etc/ssl/certs/ca.pem

- name: Init cluster
  command: kubeadm init --config /root/kubeadm-config.yaml

- name: Create kube directory
  file: 
    path: "/root/.kube"
    state: directory
    owner: "root"
    group: "root"

- name: copy admin.conf file
  command: "cp /etc/kubernetes/admin.conf /root/.kube/config"

- file:
    path: "/root/.kube/config"
    owner: "root"
    group: "root"

- file:
    path: /etc/kubernetes
    recurse: yes
    mode: "o+r"
