---
- name: Copy prom-node-exporter.yaml
  copy:
    src: "{{ role_path }}/files/prom-node-exporter.yaml"
    dest: /root/prom-node-exporter.yaml

- name: Install prometheus node exporter
  command: kubectl apply -f /root/prom-node-exporter.yaml

- name: Copy kube-state-metrics.yaml
  copy:
    src: "{{ role_path }}/files/kube-state-metrics.yaml"
    dest: /root/kube-state-metrics.yaml

- name: Install kube-state-metrics
  command: kubectl apply -f /root/kube-state-metrics.yaml

- name: Copy metrics-server.yaml
  copy:
    src: "{{ role_path }}/files/metrics-server.yaml"
    dest: /root/metrics-server.yaml

- name: Install metrics-server.yaml
  command: kubectl apply -f /root/metrics-server.yaml
