---
- name: "Cluster token"
  shell: kubeadm token create --print-join-command
  register: JOIN_COMMAND

- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name:   "K8S_HOLDER"
    command:  "{{ JOIN_COMMAND.stdout }}"
