---
- name: Get kubectl version
  shell: "kubectl version | base64 | tr -d '\n'"
  register: kubectl_version

- name: Install weavenet
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout }}"
