apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: rsdq90.wve57youpopy079m
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{ hostvars['k8s-master'].ansible_host }}
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: {{ hostvars['k8s-master'].ansible_host }}
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  certSANs:
  - {{ hostvars['k8s-master'].ansible_host }}
  extraArgs:
    apiserver-count: "3"
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: {{ hostvars['k8s-master'].ansible_host }}
controllerManager:
  extraArgs:
    node-monitor-grace-period: 16s
    node-monitor-period: 2s
    pod-eviction-timeout: 30s
dns:
  type: CoreDNS
etcd:
  external:
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    endpoints:
     - https://{{ hostvars['k8s-master'].ansible_host }}:2379
    keyFile: /etc/etcd/kubernetes-key.pem
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
networking:
  dnsDomain: cluster.local
  podSubnet: 
  serviceSubnet: 10.96.0.0/12
scheduler: {}
