---
- name: Install requiered packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker-ce repository
  command:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker-ce
  yum:
    name: docker-ce
    state: present

- name: Start docker
  systemd:
    state: started
    name: docker

- name: Enable docker
  systemd:
    name: docker
    enabled: yes

